//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelofteCheck
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BCentities : DbContext
    {
        public BCentities()
            : base("name=BCentities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Onderwerpen> Onderwerpen { get; set; }
        public virtual DbSet<Partijen> Partijen { get; set; }
        public virtual DbSet<PartijZetels> PartijZetels { get; set; }
        public virtual DbSet<Stemmingen> Stemmingen { get; set; }
        public virtual DbSet<WetScope> WetScope { get; set; }
        public virtual DbSet<Wetten> Wetten { get; set; }
    }
}
