//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelofteCheck
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartijZetels
    {
        public string PartijID { get; set; }
        public System.DateTime VanDatum { get; set; }
        public System.DateTime TotDatum { get; set; }
        public int AantalZetels { get; set; }
    
        public virtual Partijen Partijen { get; set; }
    }
}
