//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelofteCheck
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stemmingen
    {
        public string WetID { get; set; }
        public string PartijID { get; set; }
        public int Voor { get; set; }
        public int Tegen { get; set; }
        public int Blanco { get; set; }
    
        public virtual Partijen Partijen { get; set; }
        public virtual Wetten Wetten { get; set; }
    }
}
