//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BelofteCheck
{
    using System;
    using System.Collections.Generic;
    
    public partial class WetScope
    {
        public string WetID { get; set; }
        public string OnderwerpID { get; set; }
        public string Toelichting { get; set; }
    
        public virtual Onderwerpen Onderwerpen { get; set; }
        public virtual Wetten Wetten { get; set; }
    }
}
